name = "Money"
uuid = "2ab44ab6-6683-11e9-0c09-c1d7eb5e3b11"
authors = ["swiesend <sebastian@wiesendahl.de>"]
version = "0.1.0"

[deps]
FixedPointDecimals = "fb4d412d-6eee-574d-9565-ede6634db7b0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
